version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/devport
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "5174:5174"
    environment:
      - VITE_API_BASE_URL=http://45.77.172.77:5003
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    ports:
      - "27019:27017"  # Nếu bạn cần truy cập Mongo từ máy host
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
